# Generated by Django 5.2.12 on 2026-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_add_user_program_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidedprogram",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="guidedprogramday",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprogramprogress",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
