# Generated by Django 5.2.12 on 2026-03-29 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0005_userprogramprogress_completed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guidedprogram",
            options={"ordering": ["category", "plan_access", "title"]},
        ),
        migrations.AddField(
            model_name="guidedprogram",
            name="category",
            field=models.CharField(
                choices=[
                    ("wellness", "Wellness"),
                    ("coaching", "Coaching"),
                    ("educatie", "Educatie"),
                    ("suport", "Suport"),
                ],
                default="wellness",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="guidedprogram",
            name="duration_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="guidedprogram",
            name="plan_access",
            field=models.CharField(
                choices=[
                    ("basic", "BASIC Start"),
                    ("premium", "PREMIUM Flow"),
                    ("vip", "VIP Executive"),
                ],
                default="basic",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="guidedprogramday",
            name="estimated_time_minutes",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="guidedprogramday",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("check-in", "Check-in"),
                    ("exercise", "Exercise"),
                    ("reflection", "Reflection"),
                    ("reminder", "Reminder"),
                    ("journaling", "Journaling"),
                ],
                default="check-in",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userprogramprogress",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
