[phases.setup]
nixPkgs = ["nodejs_20", "python3", "pkg-config", "gcc", "gnumake"]

[phases.install]
cmds = [
  "npm install -g pnpm@9.15.9",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
