[phases.setup]
nixPkgs = ["nodejs_20", "python3", "pkg-config", "gcc", "gnumake"]

[phases.install]
cmds = [
  "NAPI_RS_FORCE_WASI=1 npm exec --yes pnpm@9.15.9 -- install --frozen-lockfile"
]

[phases.build]
cmds = ["NAPI_RS_FORCE_WASI=1 npm exec --yes pnpm@9.15.9 -- run build"]

[start]
cmd = "NAPI_RS_FORCE_WASI=1 npm exec --yes pnpm@9.15.9 -- run start"
