[phases.setup]
nixPkgs = ["nodejs_22", "python3", "pkg-config", "gcc", "gnumake"]

[phases.install]
cmds = [
  "if [ -f frontend/package.json ]; then cd frontend; fi; node -v && npm exec --yes pnpm@9.15.9 -- install --frozen-lockfile --prod=false --no-optional=false"
]

[phases.build]
cmds = [
  "if [ -f frontend/package.json ]; then cd frontend; fi; npm exec --yes pnpm@9.15.9 -- run build"
]

[start]
cmd = "if [ -f frontend/package.json ]; then cd frontend; fi; npm exec --yes pnpm@9.15.9 -- run start"
