# Generated by Django 5.2.12 on 2026-03-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_tasks", "0001_initial"),
        ("programs", "0006_alter_guidedprogram_options_guidedprogram_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="guided_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_tasks",
                to="programs.guidedprogram",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="program_day",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("program", "Program"), ("ai", "AI")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("check-in", "Check-in"),
                    ("exercise", "Exercise"),
                    ("reflection", "Reflection"),
                    ("reminder", "Reminder"),
                    ("journaling", "Journaling"),
                ],
                default="check-in",
                max_length=16,
            ),
        ),
    ]
