global:
  resolve_timeout: 5m

route:
  receiver: ops-default
  group_by: [alertname, instance]
  group_wait: 20s
  group_interval: 3m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: ops-critical
      repeat_interval: 30m

receivers:
  - name: ops-default
    email_configs:
      - to: ops@doisense.eu
        from: alerts@doisense.eu
        smarthost: smtp.gmail.com:587
        require_tls: true

  - name: ops-critical
    email_configs:
      - to: ops@doisense.eu
        from: alerts@doisense.eu
        smarthost: smtp.gmail.com:587
        require_tls: true
