# Generated by Django 5.2.12 on 2026-03-11 17:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_conversation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="ai_conversa_user_id_220de8_idx",
            old_name="ai_conversation_user_created_idx",
        ),
        migrations.AlterField(
            model_name="conversationtemplate",
            name="language",
            field=models.CharField(max_length=2, validators=[core.validators.validate_language]),
        ),
    ]
