# Generated by Django 5.2.5 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact_notification_email", models.EmailField(blank=True, max_length=254)),
                ("contact_from_email", models.EmailField(blank=True, max_length=254)),
                ("email_host", models.CharField(blank=True, max_length=255)),
                ("email_port", models.PositiveIntegerField(default=587)),
                ("email_host_user", models.CharField(blank=True, max_length=255)),
                ("email_host_password", models.CharField(blank=True, max_length=255)),
                ("email_use_tls", models.BooleanField(default=True)),
                ("email_use_ssl", models.BooleanField(default=False)),
                ("google_client_id", models.CharField(blank=True, max_length=255)),
                ("apple_client_id", models.CharField(blank=True, max_length=255)),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[("auto", "Auto"), ("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("ai_openai_api_key", models.CharField(blank=True, max_length=255)),
                ("ai_anthropic_api_key", models.CharField(blank=True, max_length=255)),
                ("ai_openai_model", models.CharField(blank=True, default="gpt-4o-mini", max_length=100)),
                (
                    "ai_anthropic_model",
                    models.CharField(blank=True, default="claude-3-5-haiku-20241022", max_length=100),
                ),
                ("ai_chat_rate_limit", models.PositiveIntegerField(default=20)),
                (
                    "ai_system_prompt_base",
                    models.TextField(
                        blank=True,
                        default="You are a supportive wellbeing assistant. Respond in the user's language. Be empathetic and concise.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_systemconfig",
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
    ]
