# Generated by Django 5.2.5 on 2026-03-08

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_systemconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="ai_max_tokens",
            field=models.PositiveIntegerField(default=1024),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="ai_request_timeout_seconds",
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="ai_temperature",
            field=models.DecimalField(decimal_places=2, default=0.70, max_digits=3),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="default_site_language",
            field=models.CharField(default="ro", max_length=2, validators=[core.validators.validate_language]),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="enabled_languages",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="stripe_price_id_premium",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="stripe_secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="stripe_webhook_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
