# Generated by Django 5.2.5 on 2026-03-08

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_systemconfig_expanded"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmspage",
            name="language",
            field=models.CharField(default="ro", max_length=2, validators=[core.validators.validate_language]),
        ),
        migrations.AddField(
            model_name="cmspage",
            name="menu_order",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="cmspage",
            name="show_in_footer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cmspage",
            name="show_in_header",
            field=models.BooleanField(default=False),
        ),
    ]
