# Generated by Django 5.2.5 on 2026-03-09

from django.db import migrations, models


def normalize_slug_suffixes(apps, schema_editor):
    CMSPage = apps.get_model("core", "CMSPage")

    for page in CMSPage.objects.filter(language="ro", slug__endswith="-ro"):
        base_slug = page.slug[:-3]
        conflict = CMSPage.objects.filter(slug=base_slug, language="ro").exclude(pk=page.pk).exists()
        if not conflict and base_slug:
            page.slug = base_slug
            page.save(update_fields=["slug"])

    for page in CMSPage.objects.filter(language="en", slug__endswith="-en"):
        base_slug = page.slug[:-3]
        conflict = CMSPage.objects.filter(slug=base_slug, language="en").exclude(pk=page.pk).exists()
        if not conflict and base_slug:
            page.slug = base_slug
            page.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_cmspage_menu_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmspage",
            name="slug",
            field=models.SlugField(max_length=120),
        ),
        migrations.RunPython(normalize_slug_suffixes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cmspage",
            constraint=models.UniqueConstraint(
                fields=("slug", "language"),
                name="core_cmspage_slug_language_uniq",
            ),
        ),
    ]
