# Generated by Django 5.2.5 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_systemconfig_stripe_basic_vip"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="backup_access_key_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_delta_max_steps",
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_force_path_style",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_region",
            field=models.CharField(blank=True, default="eu-central", max_length=64),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_retention_full_count",
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_s3_bucket",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_s3_endpoint",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_s3_path_prefix",
            field=models.CharField(blank=True, default="postgresql", max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_schedule_minutes",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="backup_secret_access_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]