# Generated by Django 5.2.12 on 2026-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_systemconfig_walg_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cmspage",
            options={"ordering": ["menu_order", "slug", "language"]},
        ),
        migrations.RenameIndex(
            model_name="userwellbeingcheckin",
            new_name="core_userwe_user_id_e99c36_idx",
            old_name="core_userwe_user_id_a8deb2_idx",
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="ai_system_prompt_base",
            field=models.TextField(
                blank=True,
                default="You are the AI ORCHESTRATOR for a wellness platform. Manage logic, analysis, and personalized wellness content by package tier (BASIC, PREMIUM, VIP). Use only anonymized data and user_id. Do not invent data. Do not provide medical diagnosis or medical advice. If data is insufficient, ask clarifying questions. Keep tone empathetic, calm, and clear. Adapt behavior strictly by package and requested output type from backend.",
            ),
        ),
    ]
